import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ThemeProvider } from "./providers/theme-provider";
import { WalletProvider } from "./providers/wallet-provider";
=======
>>>>>>> 0bafc735 (Initial commit from Create Next App)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "DeFAI Chat",
  description: "Chat with the DeFAI AI agent",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 0bafc735 (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <WalletProvider>{children}</WalletProvider>
        </ThemeProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 0bafc735 (Initial commit from Create Next App)
      </body>
    </html>
  );
}
